require 'bundler'

Bundler.require

ROOT_PATH = File.dirname(__FILE__)

require_relative 'lib/sass_config'
require_relative 'lib/core_ext'
require_relative 'lib/slim_template'
require_relative 'lib/asset_pipeline'
require_relative 'lib/server'

desc "Start the server"
task :server do
  Server.new(ROOT_PATH).start
end
