require 'bundler'

Bundler.require

ROOT_PATH = Pathname File.dirname(__FILE__)

require_relative 'lib/sass_config'
require_relative 'lib/core_ext'
require_relative 'lib/slim_template'
require_relative 'lib/asset_pipeline'
require_relative 'lib/server'

desc "Start the server"
task :server do
  Server.start do |builder|
    builder.map('/assets') { run AssetPipeline.new(ROOT_PATH) }
    builder.map('/')       { run SlimTemplate.new(ROOT_PATH)  }
  end
end

desc "Compile homepage"
task :compile do
  slim = SlimTemplate.new ROOT_PATH
  slim.compile_to '..'

  sprockets = AssetPipeline.new ROOT_PATH
  sprockets.compile_to '../assets'
end

task default: :compile
